name: questlines
description: "An RPG themed task master"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  word_generator: ^0.4.3
  collection: ^1.18.0
  string_extension: ^0.0.1
  path: ^1.8.3
  objectbox: 2.4.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  objectbox_generator: any
flutter:
  uses-material-design: true